version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 441422
       POSTGRES_DB: nestdb
    networks:
      - alpha
networks:
  alpha:

